일지 수정 pr 내용 반영 및 S3 경로 설정 코드 추가
animores/animores-server pull request #58
Opened 2024-04-30 08:37 UTC by seongyeong826

- S3 util 클래스 추가
- S3 삭제 개별 요청 -> 한번에 요청하는 방식으로 수정
- 경로 설정 관련 코드 추가 및 수정

2024-05-01 14:38 UTC, tkdlqh2 requested changes
한 3개 정도만 수정해줘
아 그리고 pr 그냥 닫지 말고 여기다 푸쉬하면 되니까 그렇게 하면 좋을듯?

2024-05-01 14:38 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/common/S3Path.java
> +}
이거 약간 Constants 처럼 쓰고 싶으면 private 생성자를 추가해서 클래스 생성을 막아줘

2024-05-01 14:38 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/common/exception/ExceptionCode.java
ExceptionCode conflict 나는 것 같은데 요거 dev 에서 merge 받아서 해결 좀 해주세용

2024-05-02 05:08 UTC, seongyeong826 commented on src/main/java/animores/serverapi/common/exception/ExceptionCode.java
ㅋㅋㅋㅋㅋ 이거 올리고나서 먼저 머지된거땜에 그런듯

2024-05-02 06:39 UTC, seongyeong826 commented on src/main/java/animores/serverapi/common/S3Path.java
> +}
완료!

2024-05-05 15:13 UTC, seongyeong826 commented on src/main/java/animores/serverapi/util/S3Util.java
> +    private String bucketName;
외부 서비스를 사용하고 항상 같은 결과를 반환하는 형태가 아니어서 util이 아닌 service형태에 가깝다고 생각되어 일반 service 클래스와 동일하게 변경함!

2024-05-05 15:14 UTC, seongyeong826 commented
@tkdlqh2 리뷰 반영해서 수정했는데 확인한번 해주십셔

2024-05-06 03:28 UTC, tkdlqh2 approved these changes

2024-05-06 03:28 UTC, merged