diary wish api 구현
animores/animores-server pull request #60
Opened 2024-04-30 10:27 UTC by seongyeong826

2024-04-30 14:37 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/service/DiaryWishService.java
> +    void removeDiaryWish(Long diaryWishId);
이거는 DiaryWish 아이디 말고 DiaryId 랑 ProfileId 를 받는 게 나을듯?

2024-04-30 15:57 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/service/DiaryWishService.java
> +    void removeDiaryWish(Long diaryWishId);
프로필 관련한거는 엑세스 토큰 말고 직접 받는거로 다음 pr때 한번에 수정할게!
아 그러네 client에서 그냥 wish인지 아닌지만 알고있으니까.. 그러면 메서드명도 좀 바꿔야겠다
수정해서 다시올리겠음

2024-05-13 15:44 UTC, tkdlqh2 requested changes
auth 적용을 해야 반영될 부분이 있을듯?
그런건 차후에 하는 걸로 하는 것도 괜찮을듯합니다.

2024-05-13 15:44 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/dto/AddDiaryWishRequest.java
> +    Long diaryId
여기도 프로필 id 입력으로 받아야 할거야

2024-05-13 15:44 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/entity/DiaryWish.java
> +})
ㅋㅋㅋ 좋은데  우리 ddl 안써서 반영은 안될듯
db 에 직접 unique 조건 만들어줭

2024-05-13 15:44 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/service/impl/DiaryWishServiceImpl.java
> +        Long profileId = 1L;    // 나중에 인증 정보에서 가져오기 param으로 받지x
profile id 는 입력으로 받는 걸로 바꾸자

2024-05-13 15:44 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/controller/DiaryWishController.java
> +
아예 컨트롤러 단에서 userService 를 받은 다음에 입력으로 받은 profileId 가 Account 에 속한 profile 인지 check 하는 로직이 있어야 될 것 같은데 어떻게 생각해?

2024-05-13 15:44 UTC, tkdlqh2 commented on src/main/java/animores/serverapi/diary/service/impl/DiaryWishServiceImpl.java
> +        DiaryWish diaryWishToDelete = diaryWishRepository.findByDiaryIdAndProfileId(profile.getId(), diary.getId())
여기 순서가 잘못됐습니다 ㅎㅎ

2024-05-14 07:28 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/dto/AddDiaryWishRequest.java
> +    Long diaryId
어엉 그거 수정중 ㅋㅋㅋㅋ 아마 swagger 브랜치 만들어놓은거 하면 다음 pr에 반영될듯 이거는 auth랑 swagger 적용 안된거까지만 해서 끝내려구

2024-05-14 07:35 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/entity/DiaryWish.java
> +})
db 수정완!

2024-05-14 07:35 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/service/impl/DiaryWishServiceImpl.java
> +        Long profileId = 1L;    // 나중에 인증 정보에서 가져오기 param으로 받지x
오키이 이것도 다음 pr!

2024-05-14 07:36 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/controller/DiaryWishController.java
> +
이것도 auth 넣고 수정한거에 체크로직 다 추가해서 pr 올릴껀데 담에 함 바주라

2024-05-14 07:44 UTC, seongyeong826 commented on src/main/java/animores/serverapi/diary/service/impl/DiaryWishServiceImpl.java
> +        DiaryWish diaryWishToDelete = diaryWishRepository.findByDiaryIdAndProfileId(profile.getId(), diary.getId())
수정완

2024-05-14 07:49 UTC, tkdlqh2 approved these changes

2024-05-14 07:49 UTC, merged